torchrun --nproc_per_node 1 \
    -m FlagEmbedding.BGE_M3.run \
    --output_dir /mnt/c/Users/thddm/Documents/model/kkt-bge-m3-unified \
    --model_name_or_path BAAI/bge-m3 \
    --train_data /mnt/c/Users/thddm/Documents/dataset/retrieval \
    --learning_rate 1e-5 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --dataloader_drop_last True \
    --normlized True \
    --temperature 0.02 \
    --query_max_len 42 \
    --passage_max_len 560 \
    --train_group_size 2 \
    --negatives_cross_device \
    --logging_steps 500 \
    --same_task_within_batch True \
    --unified_finetuning True \
    --use_self_distill True